---
# Valori di ripiego: group_vars/all.yml ha precedenza maggiore e normalmente
# sovrascrive tutto quello che sta qui.

keepalived_interface: "ens160"

vip_rancher_ip: ""
vip_rancher_prefix: 24
vip_patroni_ip: ""

keepalived_vrid_rancher: 151
keepalived_vrid_patroni: 51

keepalived_rancher_instance: "VI_NGINX"
keepalived_patroni_instance: "vrrp_1"

keepalived_priority_master: 101
keepalived_priority_step: 1

keepalived_advert_int: 1

keepalived_nginx_check_weight: 50
keepalived_nginx_check_interval: 3
nginx_health_check_port: 80

haproxy_stats_port: 7000

keepalived_config_dir: "/etc/keepalived"
